export const questions = [
    { question: "지구의 대기에는 산소가 약 21% 포함되어 있다.", answer: "O" },
    { question: "탄소는 지구상에서 가장 흔한 원소이다.", answer: "X" },
    { question: "빛은 파동과 입자의 성질을 모두 가진다.", answer: "O" },
    { question: "염산(HCl)은 산성이며, 수용액에서 수소 이온(H⁺)을 방출한다.", answer: "O" },
    { question: "달은 자체적으로 빛을 내는 천체이다.", answer: "X" },
    { question: "전류가 흐르면 자석 주변에서 전기장이 형성된다.", answer: "X" },
    { question: "모든 금속은 자석에 붙는다.", answer: "X" },
    { question: "지구의 중심부는 고체 상태이다.", answer: "O" },
    { question: "모든 생명체는 세포로 이루어져 있다.", answer: "O" },
    { question: "대류는 고온에서 저온으로 열이 전달되는 과정이다.", answer: "O" },
    { question: "원소의 주기율표에서 오른쪽으로 갈수록 금속의 성질이 강해진다.", answer: "X" },
    { question: "지구는 태양계를 포함한 은하수의 일부이다.", answer: "O" },
    { question: "광합성은 물과 이산화탄소를 산소와 포도당으로 변환하는 과정이다.", answer: "O" },
    { question: "우주에는 행성보다 별이 더 많다.", answer: "O" },
    { question: "수성은 태양계에서 가장 작은 행성이다.", answer: "O" },
    { question: "질소는 공기 중에 약 78% 포함되어 있다.", answer: "O" },
    { question: "포화 지방은 상온에서 고체 상태로 존재한다.", answer: "O" },
    { question: "원자의 중심에는 양성자와 중성자로 이루어진 핵이 있다.", answer: "O" },
    { question: "우라늄은 원자 번호가 가장 작은 원소이다.", answer: "X" },
    { question: "태양 에너지는 핵분열에 의해 생성된다.", answer: "X" },
    { question: "화학 반응에서 질량은 항상 보존된다.", answer: "O" },
    { question: "산은 일반적으로 물에 녹아 수소 이온을 방출한다.", answer: "O" },
    { question: "지구의 자전축은 23.5도 기울어져 있다.", answer: "O" },
    { question: "산성 물질은 pH 값이 7보다 크다.", answer: "X" },
    { question: "물의 끓는점은 100도이다.", answer: "O" },
    { question: "대기의 대부분은 이산화탄소로 구성되어 있다.", answer: "X" },
    { question: "모든 포유류는 폐로 호흡한다.", answer: "O" },
    { question: "금은 주기율표에서 할로젠 원소에 속한다.", answer: "X" },
    { question: "원자 번호는 원자의 양성자 수를 의미한다.", answer: "O" },
    { question: "태양은 백색왜성이다.", answer: "X" },
    { question: "식물은 빛이 없어도 광합성을 할 수 있다.", answer: "X" },
    { question: "염화나트륨(NaCl)은 이온 결합에 의해 형성된 화합물이다.", answer: "O" },
    { question: "천왕성은 해왕성보다 태양에 더 가깝다.", answer: "O" },
    { question: "자석의 같은 극끼리는 서로 밀어낸다.", answer: "O" },
    { question: "산성 비는 일반적으로 pH가 5.6보다 낮다.", answer: "O" },
    { question: "모든 물질은 원자로 이루어져 있다.", answer: "O" },
    { question: "식물의 잎에서 기공을 통해 산소와 이산화탄소가 교환된다.", answer: "O" },
    { question: "대기 중의 이산화탄소 농도가 증가하면 온실 효과가 감소한다.", answer: "X" },
    { question: "소금물은 순수한 물보다 낮은 온도에서 어는점을 가진다.", answer: "O" },
    { question: "원자력 발전은 태양광 발전보다 더 안전하다.", answer: "X" },
    { question: "광물은 지구 내부에서 형성된 자연 발생 고체 물질이다.", answer: "O" },
    { question: "산화반응은 일반적으로 에너지를 방출한다.", answer: "O" },
    { question: "초신성 폭발은 새로운 별의 탄생을 의미한다.", answer: "X" },
    { question: "흑연은 탄소 원자들이 층으로 배열된 구조를 가지고 있다.", answer: "O" },
    { question: "물은 지구에서 가장 풍부한 화합물이다.", answer: "O" },
    { question: "모든 균류는 광합성을 한다.", answer: "X" },
    { question: "전자와 양성자는 서로 반대되는 전하를 갖는다.", answer: "O" },
    { question: "수성에는 대기가 거의 없다.", answer: "O" },
    { question: "빛은 진공에서 음속보다 느리게 이동한다.", answer: "X" },
    { question: "수소는 우주에서 가장 흔한 원소이다.", answer: "O" },
    { question: "구리는 철보다 더 강하다.", answer: "X" },
    { question: "소금(NaCl)은 전해질이다.", answer: "O" },
    { question: "지구의 맨틀은 고체 상태이다.", answer: "X" },
    { question: "모든 양서류는 물에서만 생활할 수 있다.", answer: "X" },
    { question: "공기의 온도가 높아지면 습도가 증가한다.", answer: "O" },
    { question: "빛의 속도는 물보다 진공에서 더 빠르다.", answer: "O" },
    { question: "지구의 중력은 해수면에서 가장 강하다.", answer: "O" },
    { question: "칼슘은 인체에 가장 풍부한 미네랄이다.", answer: "O" },
    { question: "바람은 고기압에서 저기압으로 불어간다.", answer: "O" },
    { question: "천왕성의 자전축은 거의 수직이다.", answer: "X" },
    { question: "모든 동물은 유전 물질로 DNA를 가지고 있다.", answer: "O" },
    { question: "바이러스는 스스로 에너지를 생성할 수 있다.", answer: "X" },
    { question: "태양은 우리 은하에서 가장 큰 별이다.", answer: "X" },
    { question: "세포막은 선택적으로 물질을 투과시킨다.", answer: "O" },
    { question: "물은 pH가 7인 중성 물질이다.", answer: "O" },
    { question: "철은 공기 중에서 쉽게 녹이 슨다.", answer: "O" },
    { question: "우주의 나이는 약 137억 년이다.", answer: "O" },
    { question: "인간의 유전자는 염색체에 저장된다.", answer: "O" },
    { question: "식물은 산소를 소비하고 이산화탄소를 방출한다.", answer: "O" },
    { question: "우주 공간에서는 음파가 전파될 수 없다.", answer: "O" },
    { question: "태양계에서 목성은 토성보다 더 큰 행성이다.", answer: "O" },
    { question: "식물은 이산화탄소를 흡수하고 산소를 방출한다.", answer: "O" },
    { question: "빛의 굴절률은 매질에 따라 달라진다.", answer: "O" },
    { question: "일산화탄소는 인체에 무해하다.", answer: "X" },
    { question: "물은 지구 표면의 약 70%를 덮고 있다.", answer: "O" },
    { question: "태양의 표면 온도는 약 5,500도이다.", answer: "O" },
    { question: "암석은 시간이 지나면서 풍화되어 토양을 형성한다.", answer: "O" },
    { question: "모든 기체는 열을 가하면 팽창한다.", answer: "O" },
    { question: "포도당은 탄소, 수소, 산소로 이루어진다.", answer: "O" },
    { question: "소리는 음파로 전달된다.", answer: "O" },
    { question: "모든 물질은 고체, 액체, 기체 중 한 상태로만 존재한다.", answer: "X" },
    { question: "수소는 물의 주요 구성 요소이다.", answer: "O" },
    { question: "지구 자전의 속도는 위도에 따라 다르다.", answer: "O" },
    { question: "호랑이는 야생에서 100년까지 살 수 있다.", answer: "X" },
    { question: "지구의 자전은 하루 동안의 시간을 결정한다.", answer: "O" },
    { question: "토성의 고리는 얼음과 암석으로 이루어져 있다.", answer: "O" },
    { question: "지구는 태양에 가장 가까운 행성이다.", answer: "X" },
    { question: "동물은 대사 과정에서 에너지를 생성한다.", answer: "O" },
    { question: "핵산은 유전 정보를 저장하는 역할을 한다.", answer: "O" },
    { question: "모든 금속은 전기를 잘 전도한다.", answer: "O" },
    { question: "대류는 물체가 직접 접촉하지 않고 열을 전달하는 과정이다.", answer: "X" },
    { question: "인간의 체온은 보통 약 37도이다.", answer: "O" },
    { question: "모든 식물은 씨앗을 통해 번식한다.", answer: "X" },
    { question: "물은 액체 상태에서 가장 밀도가 높다.", answer: "O" },
    { question: "달의 중력은 지구의 중력보다 강하다.", answer: "X" },
    { question: "태양은 하루 동안 동쪽에서 서쪽으로 이동한다.", answer: "O" }
    { question: "빙하는 해수면을 높이는 역할을 한다.", answer: "O" },
    { question: "지구의 표면은 70%가 물로 덮여 있다.", answer: "O" },
    { question: "백색 왜성은 중성자별보다 크다.", answer: "X" },
    { question: "대기 중의 산소는 식물의 광합성으로 생성된다.", answer: "O" },
    { question: "공룡은 중생대에 멸종되었다.", answer: "O" },
    { question: "모든 파동은 진동을 통해 에너지를 전달한다.", answer: "O" },
    { question: "온도가 높을수록 공기의 밀도가 높아진다.", answer: "X" },
    { question: "암석은 열과 압력에 의해 변성암으로 변할 수 있다.", answer: "O" },
    { question: "토성의 고리는 행성의 중력에 의해 형성된 것이다.", answer: "O" },
    { question: "적혈구는 산소를 운반하는 역할을 한다.", answer: "O" },
    { question: "태양은 약 45억 년 전에 형성되었다.", answer: "O" },
    { question: "바람은 기압 차이에 의해 발생한다.", answer: "O" },
    { question: "빛의 속도는 우주에서 변하지 않는다.", answer: "X" },
    { question: "태풍은 저기압에서 발생하는 기상 현상이다.", answer: "O" },
    { question: "대류권이란 대기의 가장 아래층에 위치한 층이다.", answer: "O" },
    { question: "혈장은 혈액의 약 90%를 차지한다.", answer: "X" },
    { question: "태양은 주로 수소와 헬륨으로 구성되어 있다.", answer: "O" },
    { question: "플라스틱은 자연적으로 생분해되지 않는다.", answer: "O" },
    { question: "세포핵은 유전 정보를 저장하는 장소이다.", answer: "O" },
    { question: "모든 산은 수소 이온을 방출한다.", answer: "O" },
    { question: "헬륨은 우주에서 두 번째로 흔한 원소이다.", answer: "O" },
    { question: "전자기파는 매질이 필요 없다.", answer: "O" },
    { question: "지구의 가장 큰 기후 변화 요인은 인간 활동이다.", answer: "O" },
    { question: "달은 지구에서 가장 큰 위성이다.", answer: "X" },
    { question: "백혈구는 인체의 면역 시스템에 중요한 역할을 한다.", answer: "O" },
    { question: "달의 표면은 주로 화산암으로 이루어져 있다.", answer: "O" },
    { question: "우라늄은 원자로에서 핵분열을 일으킨다.", answer: "O" },
    { question: "빛은 입자이면서 동시에 파동의 성질을 갖는다.", answer: "O" },
    { question: "탄수화물은 에너지를 저장하는 주요 물질이다.", answer: "O" },
    { question: "태양 에너지는 화석 연료보다 훨씬 더 오랫동안 존재할 수 있다.", answer: "O" },
    { question: "물이 수증기로 변할 때 흡열 반응이 일어난다.", answer: "O" },
    { question: "금속은 일반적으로 열과 전기를 잘 전달한다.", answer: "O" },
    { question: "탄소는 지구상에서 네 번째로 흔한 원소이다.", answer: "O" },
    { question: "지구는 자전으로 인해 북반구와 남반구가 서로 다른 계절을 가진다.", answer: "O" },
    { question: "가스는 일반적으로 고체보다 밀도가 높다.", answer: "X" },
    { question: "적도는 지구에서 가장 긴 경선이다.", answer: "X" },
    { question: "모든 동물은 물을 필요로 한다.", answer: "O" },
    { question: "전자는 원자핵 주위에서 궤도 운동을 한다.", answer: "O" },
    { question: "포유류는 대부분 체온이 일정하다.", answer: "O" },
    { question: "지구의 공전 궤도는 타원형이다.", answer: "O" },
    { question: "지구는 금성과 가장 가까운 행성이다.", answer: "X" },
    { question: "강수량은 대기의 수증기량에 영향을 받는다.", answer: "O" },
    { question: "달의 중력은 지구의 약 1/6이다.", answer: "O" },
    { question: "지진은 지구의 판이 움직이면서 발생한다.", answer: "O" },
    { question: "태양계에서 지구는 다섯 번째로 큰 행성이다.", answer: "X" },
    { question: "고체는 분자가 고정된 위치에 있다.", answer: "O" },
    { question: "수증기는 대기 중에서 온실효과를 일으킨다.", answer: "O" },
    { question: "온실 가스는 지구의 온도를 낮추는 역할을 한다.", answer: "X" },
    { question: "토양은 생물에게 필수적인 영양분을 제공한다.", answer: "O" },
    { question: "포화 지방은 건강에 해로울 수 있다.", answer: "O" },
    { question: "목성은 태양계에서 가장 많은 위성을 가진 행성이다.", answer: "O" },
    { question: "오존층은 자외선을 흡수하여 지구를 보호한다.", answer: "O" },
    { question: "산호는 해양 생태계에 중요한 역할을 한다.", answer: "O" },
    { question: "지구의 자전은 24시간 동안 한 바퀴 돈다.", answer: "O" },
    { question: "산성화는 해양 생물에 해로운 영향을 미친다.", answer: "O" },
    { question: "바다는 대기 중의 이산화탄소를 흡수한다.", answer: "O" },
    { question: "모든 식물은 뿌리, 줄기, 잎으로 이루어져 있다.", answer: "X" },
    { question: "화산은 지구 내부의 열이 표면으로 방출되는 현상이다.", answer: "O" },
    { question: "고래는 포유류이다.", answer: "O" },
    { question: "우주에는 은하가 약 1천억 개 이상 있다.", answer: "O" },
    { question: "비행기가 날 수 있는 것은 양력 때문이다.", answer: "O" },
    { question: "원자력 발전은 이산화탄소를 배출하지 않는다.", answer: "O" },
    { question: "지구의 중력은 위도에 따라 다르다.", answer: "X" },
    { question: "산소는 인체에서 가장 풍부한 원소이다.", answer: "O" },
    { question: "지구의 자전 속도는 고정되어 있다.", answer: "X" },
    { question: "가열하면 기체는 팽창한다.", answer: "O" },
    { question: "지구에서 가장 풍부한 원소는 규소이다.", answer: "X" },
    { question: "원자의 크기는 원자 번호에 따라 변한다.", answer: "O" },
    { question: "공기는 혼합물이다.", answer: "O" },
    { question: "백금은 은보다 더 강한 원소이다.", answer: "X" },
    { question: "태양은 황색 왜성이다.", answer: "O" },
    { question: "빙하는 담수로 이루어져 있다.", answer: "O" },
    { question: "전류는 전자의 흐름에 의해 발생한다.", answer: "O" },
    { question: "모든 생물은 에너지를 필요로 한다.", answer: "O" },
    { question: "빛은 공기보다 물에서 빠르게 이동한다.", answer: "X" },
    { question: "물 분자는 두 개의 수소와 하나의 산소로 구성되어 있다.", answer: "O" },
    { question: "빛은 파장에 따라 다양한 색으로 분산된다.", answer: "O" },
    { question: "바다는 지구의 약 71%를 덮고 있다.", answer: "O" },
    { question: "지구의 북반구와 남반구는 계절이 반대이다.", answer: "O" },
    { question: "화산 활동은 대기 중에 이산화탄소를 방출한다.", answer: "O" },
    { question: "태양계는 약 45억 년 전에 형성되었다.", answer: "O" },
    { question: "암석은 시간이 지남에 따라 토양으로 변할 수 있다.", answer: "O" },
    { question: "수온이 높을수록 물의 산소 용해도가 증가한다.", answer: "X" },
    { question: "지구는 태양 주위를 한 번 도는 데 365일이 걸린다.", answer: "O" },
    { question: "목성은 태양계에서 가장 큰 행성이다.", answer: "O" },
    { question: "중성자별은 매우 밀도가 높은 천체이다.", answer: "O" },
    { question: "대류권에서는 고도에 따라 기온이 낮아진다.", answer: "O" },
    { question: "바다는 산소와 수소로 이루어져 있다.", answer: "O" },
    { question: "고체는 일반적으로 가스보다 밀도가 높다.", answer: "O" },
    { question: "온실 효과는 지구를 따뜻하게 유지하는 역할을 한다.", answer: "O" },
    { question: "철은 구리보다 더 잘 녹는다.", answer: "X" },
    { question: "태양풍은 태양에서 방출되는 입자들이다.", answer: "O" },
    { question: "모든 곤충은 날개를 가지고 있다.", answer: "X" },
    { question: "포유류는 고온의 피를 가지고 있다.", answer: "O" }
];
